### ISSUE TITLE
Update receiver callback definition

### ISSUE THREAD

**Issue by gioblu** [4ib3r/MyTransportPJON#2]
Ciao @4ib3r I see here:
https://github.com/4ib3r/MyTransportPJON/blob/master/MyTransportPJON.h#L62

the receiver callback is in its outdated version, change in:
```cpp
void receiver_function(uint8_t *payload, uint16_t length, const PJON_Packet_Info &packet_info) {
```
to be compatible with PJON new versions.

In terms of codestyle I suggest you to use the suggested parameter names for the callback so `length` instead of `l`, so code from the PJON documentation or examples will fit in out-of-the-box.

Thank you very much for MyTransportPJON 👍

**Comment by 4ib3r** [comment]
Hi, this is old version, I created new implementation based on MySensors 2.3 in repository https://github.com/4ib3r/MySensors
