### ISSUE TITLE
Support conditional serial debug 

### ISSUE THREAD

**Issue by gioblu** [4ib3r/MyTransportPJON#3]
Ciao @4ib3r I see here:
https://github.com/4ib3r/MyTransportPJON/blob/master/MyTransportPJON.h#L63
print for debug using the Serial object.

Why not to support conditional (maybe by default disabled) debug print activation with a predefined constant?

Something like:
```cpp
#define MTP_DEBUG // Activate MyTransportPJON debug print
#include "MyTransportPJON.h"
```

So users who need the serial port for other tasks will not need to edit the MyTransportPJON source to disable it. Thank you very much for MyTransportPJON 👍

**Comment by 4ib3r** [comment]
Hi, this is old version, I created new implementation based on MySensors 2.3 in repository https://github.com/4ib3r/MySensors
In that version I added `PJON_DEBUG` constant for that purposes
